name: Deploy to AWS desarrollo

on:
  push:
    branches:
      - desarrollo  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          printf "%s" "${{ secrets.AWS_SSH_KEY }}" > aws_key.pem
          chmod 600 aws_key.pem

          

      - name: Connect to EC2 and Pull Changes
        run: |
          ssh -o StrictHostKeyChecking=no -i aws_key.pem juan@ec2-3-92-214-254.compute-1.amazonaws.com << 'EOF'
            cd /home/juan/backend-tfg
            git checkout desarrollo
            git pull origin desarrollo 
            echo "${{ secrets.LARAVEL_ENV_DESARROLLO }}" > /home/juan/backend-tfg/.env
            composer update
            php artisan migrate:refresh --seed
            echo " Deteniendo cualquier proceso en el puerto 8000..."
            fuser -k 8000/tcp || true
            echo " Iniciando Laravel en el puerto 8000..."
            nohup php artisan serve --host=0.0.0.0 --port=8000 > /dev/null 2>&1 &
            echo "✅ Despliegue completado."
            exit
          EOF
